#!/bin/bash
#SBATCH -J LC-test
#SBATCH --nodes=1 
#SBATCH -p gpu
#SBATCH --mail-user=cfs4@st-andrews.ac.uk
#SBATCH --mail-type=ALL

# set variables for python script
train_dir='/home/cfs4/NN-dev/training-sets/bands'
out_dir='/home/cfs4/PhCW2022/learning-curve'
out_name='LC-test'
epochs=20
patience=5
learning_rate=0.00002
split=0.025

eval "$(conda shell.bash hook)"
conda activate deep

python learning_curve.py --train_dir $train_dir --out_dir $out_dir --out_name $out_name --epochs $epochs --patience $patience --learning_rate $learning_rate --split $split
